### ISSUE TITLE
node sass don´t work on deploy

### ISSUE THREAD

**Issue by bueno12223** [bueno12223/bueno12223#1]
I am using Heroku to deploy my app, I start the project on Windows, some days ago I install Ubuntu and end my project here, I did a push to the Heroku repository since Windows but don´t recognize the files whit .scss, I run in both OS without any problem but when I deploy It gives that error.

``` 
ERROR in ./src/frontend/components/styles/recomendations.scss
       Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
       ModuleError: Module Error (from ./node_modules/sass-loader/dist/cjs.js):
       ENOENT: no such file or directory, scandir '/tmp/build_ff97ecaa/node_modules/node-sass/vendor'
           at Object.emitError (/tmp/build_ff97ecaa/node_modules/webpack/lib/NormalModule.js:539:6)
           at getSassImplementation (/tmp/build_ff97ecaa/node_modules/sass-loader/dist/utils.js:55:21)
           at Object.loader (/tmp/build_ff97ecaa/node_modules/sass-loader/dist/index.js:27:59)
        @ ./src/frontend/components/recomendations.jsx 2:0-38
        @ ./src/frontend/pages/main.jsx 9:0-58 113:39-53
        @ ./src/frontend/routes/app.js 2:0-33 6:42-46
        @ ./src/frontend/index.js 3:0-31 4:51-54
```
For some reason installing the node modules take too much time, and after like 5 minutes gives me the error.

**Comment by bueno12223** [comment]
I tried too to disable the Heroku cache but give the same issue.

**Comment by bueno12223** [comment]
I nail it, I have to update my node, it had the 10.X version, too late, and move Webpack to normal dependences.
